### ISSUE TITLE
"switching to javascript ruleset" - Invalid ruleset provided

### ISSUE THREAD

**Issue by MarkusAJacobsen** [apisyouwonthate/style-guide#18]
Hi, we used the apisyouwonthate.yaml and openapi.yaml files for our spectral settings.
The builds stopped working yesterday and I see that you have removed those files and replaced with Javascript-based rulesets.

Tried to replace the file references with `@apisyouwonthate/style-guide` to the spectral config, but I get "Invalid ruleset provided" error.

To replicate:
`npm install --save -D @apisyouwonthate/style-guide`

Add `@apisyouwonthate/style-guide` to .spectral.yaml#extends

Run `spectral lint openapi.yaml`

-----------------------
@apisyouwonthate/style-guide: 1.1.0
@stoplight/spectral-cli: 6.4.1

**Comment by philsturgeon** [comment]
Sorry about that @MarkusAJacobsen. I had no idea anyone was using that awkward stuff, but this new package is intended for use and will get better and better especially when I add tests.

This issue was down to my having some stuff installed locally that you don't, but I've marked them as dependencies and published a new version.

v1.1.1 should work!
